version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/cert:/etc/letsencrypt:ro
    depends_on:
      - web
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: gunicorn ewsdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
      - ./static:/usr/src/static
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306/tcp"
    env_file:
      - ./backend/django.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/data/conf.d:/etc/mysql/conf.d
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/cert:/etc/letsencrypt:rw
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email mail@example.com --agree-tos --no-eff-email
      -d example.com
    depends_on:
      - nginx
